version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_PASSWORD: 12345!
      MYSQL_ROOT_PASSWORD: 12345!
      MYSQL_DATABASE: snapai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
volumes:
  snapai: